
INPUT_FILE_PATH = "iris_data_class_binary.csv"
OUTPUT_FILE_PATH = "iris_data_output_data.csv"
OUTPUT_REPORT_PATH = "iris_ml_results.txt"
GENERATE_PLOTS = True

RUN_MLP_CLASSIFIER = True
RUN_LOGISTIC_REGRESSION = True
RUN_RANDOMFOREST_CLASSIFIER = True
RUN_ADA_BOOST = True
RUN_GRADIENT_BOOST = True
RUN_DECISIONTREE_CLASSIFIER = True
RUN_SVM = True
RUN_GAUSSIAN_CLASSIFIER = True
RUN_GAUSSIANB_CLASSIFIER = True
RUN_KNEAREST_NEIGHBORS = True
RUN_XGBOOST_CLASSIFIER = True


